### ISSUE TITLE
X-ui is not reachable when using the default Docker command

### ISSUE THREAD

**Issue by mightydaduser** [Chasing66/beautiful_docker#1]
X-ui is not reachable when using the default Docker command with the args "--network=host".

I tried "-p 54321:54321" and it worked.

I am using an Ubuntu 20.04 AArch64 system, the firewall ufw is not running:

#ufw status
#Status: inactive

**Comment by mightydaduser** [comment]
> X-ui is not reachable when using the default Docker command with the args "--network=host".
> 
> I tried "-p 54321:54321" and it worked.
> 
> I am using an Ubuntu 20.04 AArch64 system, the firewall ufw is not running:
> 
> #ufw status #Status: inactive

It seems that the problem came form the VPS itself. I've tested other Docker apps, none of them worked under "--network=host", lol.

**Comment by Chasing66** [comment]
We must use host network since we are going to expose the port to launch socks4 or anyother proxy.
Please check as below: 
1. container status when you use host network. 
2. whether 54321 port is listened when you start it
3. check whether 54321 port is accessable with telnet

**Comment by Chasing66** [comment]
If no  more question from you, I will close this issue.
