### ISSUE TITLE
using multiple x-ui container in docker 

### ISSUE THREAD

**Issue by SooranSaeed** [Chasing66/beautiful_docker#10]
guys thank you so much for your x-ui , I want to run this container multiple on docker can you tell me how can this command would be ?

**Comment by SooranSaeed** [comment]
@Chasing66 @ForkRun  can you help me

**Comment by enwaiax** [comment]
Why do you want run multiple x-ui containers?

**Comment by SooranSaeed** [comment]
because I have several friend and partner and I want to take them v2ray connection to them I like to run miltiple x-ui on several ip to condom from ban in iran

**Comment by enwaiax** [comment]
I ssuggest you change the configuration "listening address" to different IP to make it. The listening address by default is 127.0.0.1 if you leave it empty. You can change to your IP if you have several IPs on the host.

**Comment by enwaiax** [comment]
Close due to no more response
