### ISSUE TITLE
x-ui docker成功后无法访问

### ISSUE THREAD

**Issue by xuewlcn** [Chasing66/beautiful_docker#3]
<img width="1204" alt="image" src="https://user-images.githubusercontent.com/88409788/175503092-cc90f167-295a-47bb-af20-2d1d509e84af.png">

**Comment by Chasing66** [comment]
没试过在windows上跑，可能跟你本地网卡有关系

**Comment by Guichen1210** [comment]
> 
尝试关闭防火墙后试试
