### ISSUE TITLE
How to migrate x-ui into v2-ui?

### ISSUE THREAD

**Issue by nghiepit** [Chasing66/beautiful_docker#7]
After exec into the container running
```
$ /root/x-ui v2-ui
```
And failed to migrate
> migrate from v2-ui failed: init v2-ui database failed: unable to open database file: no such file or directory

The try to mount `./v2-ui:/etc/v2-ui`
> migrate from v2-ui failed: get v2-ui inbounds failed: no such table: inbound

**Comment by Chasing66** [comment]
As described in [vaxilu/x-ui](https://github.com/vaxilu/x-ui), you can only migrate from v2-ui to x-ui but can't migrate x-ui into v2-ui. Besides, this project is docker based which is different from host based x-ui. The migration is never tested on docker based image.

The error here may be becase it can't not read the v2-ui configration files. I'd suggest you add it by yourself manually if you don't have many configrations.
